import Head from 'next/head';
import { NextPage } from 'next';
import Image from 'next/image';
import Layout from 'src/components/Layout';
import { getGames } from './../lib/game';

interface IGame {
  games?: any;
}

const Home: NextPage<IGame> = ({ games }) => {
  console.log('games', games);

  return (
    <>
      <Head>
        <title>NFT Games App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <ul className="games">
          {games.map((game: any) => (
            <li key={game.id}>
              <Image src={game.background_image} alt={game.name} width={452} height={452} />
            </li>
          ))}
        </ul>
      </Layout>
    </>
  );
};

export const getStaticProps = async () => {
  const games = await getGames();
  return {
    props: {
      games,
    },
  };
};

export default Home;
