import Head from 'next/head';
import { NextPage } from 'next';
import Image from 'next/image';
import Layout from 'src/components/Layout';
import { getGames } from './../lib/game';
import { useEffect, useState } from 'react';

interface IGame {
  games?: any;
}

const Home: NextPage<IGame> = ({ games }) => {
  const [db, setDb] = useState(games);
  //console.log('games', games);

  const searchGame = (name: string) => {
    if (name) {
      // games = games.filter((game: any) => game.name == name);
      games = games.filter((game: any) => game.name.match(name));
    } else {
      //games = db;
    }
    console.log(games);
    setDb(games);
  };

  return (
    <>
      <Head>
        <title>NFT Games App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout searchGame={searchGame}>
        <ul className="games">
          {db.map((game: any) => (
            <li key={game.id}>
              <Image src={game.background_image} alt={game.name} width={452} height={452} />
            </li>
          ))}
        </ul>
      </Layout>
    </>
  );
};

export const getStaticProps = async () => {
  const games = await getGames();
  return {
    props: {
      games,
    },
  };
};

export default Home;
